// Generated by CoffeeScript 2.7.0
(function() {
  var assert, formatString, mod, pad;

  assert = require("assert");

  ({formatString, pad, mod} = require("../src/core/utils.coffee"));

  describe("formatString", function() {
    return it("must format string with several args", function() {
      var expect, out;
      out = formatString("{0} is dead, but {1} is alive! {0} {2}", ["ASP", "ASP.NET"]);
      expect = "ASP is dead, but ASP.NET is alive! ASP {2}";
      return assert.equal(out, expect);
    });
  });

  describe("pad", function() {
    it("must pad small nums", function() {
      assert.equal(pad(4, 4), "0004");
      assert.equal(pad(4, 5), "00004");
      return assert.equal(pad(123, 5), "00123");
    });
    return it("must not truncate", function() {
      assert.equal(pad(123, 2), "123");
      return assert.equal(pad(123, 1), "123");
    });
  });

  describe("mod", function() {
    it("must calculate modulo of positive values", function() {
      assert.equal(0, mod(0, 5));
      assert.equal(1, mod(1, 5));
      assert.equal(2, mod(2, 5));
      assert.equal(0, mod(25, 5));
      assert.equal(1, mod(26, 5));
      return assert.equal(2, mod(27, 5));
    });
    return it("must calculate modulo of negative values mathematically", function() {
      assert.equal(0, mod(-25, 5));
      assert.equal(1, mod(-24, 5));
      return assert.equal(2, mod(-23, 5));
    });
  });

}).call(this);
