// Generated by CoffeeScript 2.7.0
(function () {
  //taken from http://www.html5canvastutorials.com/advanced/html5-canvas-mouse-coordinates/
  exports.getCanvasCursorPosition = function (e, canvas) {
    var rect;
    if (e.type === "touchmove" || e.type === "touchstart" || e.type === "touchend") {
      e = e.touches[0];
    }
    if (e.clientX != null) {
      rect = canvas.getBoundingClientRect();
      return [e.clientX - rect.left, e.clientY - rect.top];
    }
  };
}).call(this);
