// Generated by CoffeeScript 2.7.0
(function () {
  var ContextDelegate, runCommands;

  exports.ContextDelegate = ContextDelegate = class ContextDelegate {
    constructor() {
      this.commands = [];
    }

    moveTo(x, y) {
      return this.commands.push(1, x, y);
    }

    lineTo(x, y) {
      return this.commands.push(2, x, y);
    }

    bezierCurveTo(x1, y1, x2, y2, x3, y3) {
      return this.commands.push(3, x1, y1, x2, y2, x3, y3);
    }

    closePath() {
      return this.commands.push(4);
    }

    reset() {
      return (this.commands = []);
    }

    take() {
      var c;
      c = this.commands;
      this.commands = [];
      return c;
    }
  };

  exports.runCommands = runCommands = function (context, cs) {
    var i, n;
    i = 0;
    n = cs.length;
    while (i < n) {
      switch (cs[i]) {
        case 1:
          context.moveTo(cs[i + 1], cs[i + 2]);
          i += 3;
          break;
        case 2:
          context.lineTo(cs[i + 1], cs[i + 2]);
          i += 3;
          break;
        case 3:
          context.bezierCurveTo(cs[i + 1], cs[i + 2], cs[i + 3], cs[i + 4], cs[i + 5], cs[i + 6]);
          i += 7;
          break;
        case 4:
          context.closePath();
          i += 1;
          break;
        default:
          throw new Error(`Unnown drawing command ${cs[i]}`);
      }
    }
  };
}).call(this);
