// Generated by CoffeeScript 2.7.0
(function () {
  "use strict";
  exports.formatString = function (s, args) {
    return s.replace(/{(\d+)}/g, function (match, number) {
      var ref;
      return (ref = args[number]) != null ? ref : match;
    });
  };

  exports.pad = function (num, size) {
    var s;
    s = num + "";
    while (s.length < size) {
      s = "0" + s;
    }
    return s;
  };

  exports.parseIntChecked = function (s) {
    var v;
    v = parseInt(s, 10);
    if (Number.isNaN(v)) {
      throw new Error(`Bad number: ${s}`);
    }
    return v;
  };

  exports.parseFloatChecked = function (s) {
    var v;
    v = parseFloat(s);
    if (Number.isNaN(v)) {
      throw new Error(`Bad number: ${s}`);
    }
    return v;
  };

  //mathematical modulo
  exports.mod = function (i, n) {
    return ((i % n) + n) % n;
  };
}).call(this);
